"""initial migration

Revision ID: a7ecfad8ed31
Revises:
Create Date: 2025-06-07 11:18:14.637311

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

"""This migration is for current DB schema
If you need to create tables - delete this migration and create new one
with `make migration && make migrate` command"""

# revision identifiers, used by Alembic.
revision: str = "a7ecfad8ed31"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
