"""initial migration

Revision ID: a7ecfad8ed31
Revises:
Create Date: 2025-06-07 11:18:14.637311

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a7ecfad8ed31"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_statistics",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_testing_exercises", sa.Integer(), nullable=False),
        sa.Column("total_new_words", sa.Integer(), nullable=False),
        sa.Column("total_irregular_verbs", sa.Integer(), nullable=False),
        sa.Column("new_users", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("date"),
    )
    op.create_index(
        "ix_daily_statistics_date", "daily_statistics", ["date"], unique=False
    )
    op.create_table(
        "new_words",
        sa.Column("section", sa.String(length=64), nullable=False),
        sa.Column("subsection", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("russian", sa.String(length=256), nullable=False),
        sa.Column("english", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("section", "subsection", "id"),
    )
    op.create_table(
        "testing_exercises",
        sa.Column("section", sa.String(length=64), nullable=False),
        sa.Column("subsection", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test", sa.String(length=256), nullable=False),
        sa.Column("answer", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("section", "subsection", "id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("registration_date", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("full_name", sa.String(length=256), nullable=True),
        sa.Column("tg_login", sa.String(length=32), nullable=True),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("reminder_time", sa.Time(), nullable=True),
        sa.Column("time_zone", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "user_progress",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("exercise_type", sa.String(length=64), nullable=False),
        sa.Column("exercise_section", sa.String(length=64), nullable=False),
        sa.Column("exercise_subsection", sa.String(length=64), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint(
            "user_id",
            "exercise_type",
            "exercise_section",
            "exercise_subsection",
            "exercise_id",
        ),
    )
    op.create_table(
        "user_words_learning",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("section", sa.String(length=64), nullable=False),
        sa.Column("subsection", sa.String(length=64), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("success", sa.Integer(), nullable=False),
        sa.Column("next_review_date", sa.Date(), nullable=False),
        sa.Column("add_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["section", "subsection", "exercise_id"],
            ["new_words.section", "new_words.subsection", "new_words.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "section", "subsection", "exercise_id"),
    )
    op.create_index(
        "ix_user_section",
        "user_words_learning",
        ["user_id", "section", "subsection"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_words_learning_section"),
        "user_words_learning",
        ["section"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_words_learning_subsection"),
        "user_words_learning",
        ["subsection"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_words_learning_user_id"),
        "user_words_learning",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_words_learning_user_id"),
        table_name="user_words_learning",
    )
    op.drop_index(
        op.f("ix_user_words_learning_subsection"),
        table_name="user_words_learning",
    )
    op.drop_index(
        op.f("ix_user_words_learning_section"),
        table_name="user_words_learning",
    )
    op.drop_index("ix_user_section", table_name="user_words_learning")
    op.drop_table("user_words_learning")
    op.drop_table("user_progress")
    op.drop_table("users")
    op.drop_table("testing_exercises")
    op.drop_table("new_words")
    op.drop_index("ix_daily_statistics_date", table_name="daily_statistics")
    op.drop_table("daily_statistics")
    # ### end Alembic commands ###
